### ISSUE TITLE
每次开机进入桌面后，过一会突然黑屏重启

### ISSUE THREAD

**Issue by Esc-2** [gkShine/MSI_GS65_9SE_EFI#1]
笔记本是gs65，9750H，2070m版本
进入12.1系统后会突然卡住，而后自动重启，重启完成就没问题了，上一版本的efi没出现这个问题

**Comment by Esc-2** [comment]
大佬可以分析下原因吗？

**Comment by gkShine** [comment]
> 大佬可以分析下原因吗？

试试  reset nvram

**Comment by Esc-2** [comment]
感谢，近期没出现开机重启的情况，就没重置nvram。一切正常，功能完好，祝大佬生活愉快！
