### ISSUE TITLE
大佬，之前用的是 clover 引导的 macOS Catalina（10.15.7），直接替换成你的这个OC后能进到oc的启动项选择界面，但是只能看到 windows，看不到其他的选项是怎么回事呀

### ISSUE THREAD

**Issue by elewen** [gkShine/MSI_GS65_9SE_EFI#3]
大佬，之前用的是 clover 引导的 macOS Catalina（10.15.7），直接替换成你的这个OC后能进到oc的启动项选择界面，但是只能看到 windows，看不到其他的选项，无法选择启动到 macOS  Catalina 系统。是不支持吗

**Comment by elewen** [comment]
> 大佬，之前用的是 clover 引导的 macOS Catalina（10.15.7），直接替换成你的这个OC后能进到oc的启动项选择界面，但是只能看到 windows，看不到其他的选项，无法选择启动到 macOS Catalina 系统。是不支持吗

同 sg65-9SE

**Comment by gkShine** [comment]
在oc启动界面 按空格 然后 执行  clean nvram

**Comment by elewen** [comment]
> 在oc启动界面 按空格 然后 执行 clean nvram

执行 clean nvram 屏幕变黑色背景了，一直等了几分钟没反应，我只能强制关机再启动，然后还是那样，不知道怎么办了。

**Comment by elewen** [comment]
看不到其他的选项的问题已解决。但是现在产生了两个新的问题。

第一个问题：我下载的是仓库中最后一次提交的oc配置文件，我看提交信息写着更新到了 oc 0.8.1，但是当我用 openCore Configurator v2.61.1.0 编辑 config. plist 文件时出现下图所示的提示信息该怎么解决？ps：我按照网上说的两种方式均无法成功获取到当前 oc 引导的版本号，版本号均显示 “0.0.0”。

openCore Configurator v2.61.1.0 的截图不好贴，文字描述为：
“您似乎加载了一个旧版本的opencore引导程序，此应用为0.8.1或更高版本创建配置文件。”


第二个问题：在oc启动选择系统界面偶尔会出现无法使用内置方向键选择要启动的系统的问题，此问题网上已有人提出了，但是貌似没找到解决办法，不知道有没有解决办法。

**Comment by gkShine** [comment]
问题一，我没用OpenCore Configurator  用的是 OCAuxiliaryTools
问题二，这个问题依旧存在，只是我用了外接键盘就没在意

**Comment by elewen** [comment]
> 问题一，我没用OpenCore Configurator 用的是 OCAuxiliaryTools 问题二，这个问题依旧存在，只是我用了外接键盘就没在意

了解了 感谢大佬
