### ISSUE TITLE
怎么刷黑苹果，什么时候出个教程，还有能否说说注意事项

### ISSUE THREAD

**Issue by gaodenger** [gkShine/MSI_GS65_9SE_EFI#5]

**Comment by gkShine** [comment]
教程不好搞，因为我这是有mac电脑才能制作安装盘。所以最好的办法就是去网上搜傻瓜式安装包iso的，然后刻到u盘里，再用磁盘工具打开u盘里的EFI盘，下载我配置覆盖即可。现在安装黑苹果已经很方便了，注意对应的系统版本即可。
